<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCJWA4N0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCJWA4N0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCJWA4N0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCJWA4N0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCJWA4N0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CJWA4N0',
    'container.build_id' => '7d9cf026',
    'container.build_time' => 1551910474,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCJWA4N0');
