<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerADbscbj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerADbscbj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerADbscbj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerADbscbj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerADbscbj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ADbscbj',
    'container.build_id' => 'db21eddc',
    'container.build_time' => 1551971350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerADbscbj');
